---
- name: Fail if any repo has gpgcheck=0
  hosts: all
  become: true
  tasks:
    - name: Slurp files
      ansible.builtin.slurp:
        src:  "/etc/yum.repos.d/redhat.repo"
      register: yum_repos

    - name: Slurp files
      ansible.builtin.debug:
        msg: "{{ yum_repos }}"

    - name: Use set_fact to combine yum_repos into single dictionary
      ansible.builtin.set_fact:
        yum_repos_combined: "{{ yum_repos_combined | default({}) | combine({yum_repos.source:
          yum_repos.content|b64decode|community.general.from_ini } ) }}"
      #loop: "{{ yum_repos.results }}"

    - name: Assert gpgcheck is enabled
      loop: "{{ yum_repos_combined |dict2items }}"
      ansible.builtin.assert:
        that: "{{ item.value[item.value|first]['gpgcheck'] | bool }}"
