---
- name: Quick test of connectivity to Windows host
  hosts: windows
  gather_facts: false

  vars_files:
    - secrets.yml

  tasks:
    - name: Quick win_ping test
      ansible.windows.win_ping:

