---
- name: Print All Incoming Splunk Payloads
  hosts: all
  sources:
    - ansible.builtin.webhook:
        host: 0.0.0.0
        port: 5000
#    - ansible.eda.range:
#        limit: 1

  rules:
    - name: Catch and Print Any Event
      condition: true
      action:
        debug:
          msg: "Incoming Payload Received: {{ event }}"

...
