- name: Install and enable firewalld
  hosts: all
  become: true

  tasks:
    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Start and enable firewalld service
      ansible.builtin.systemd_service:
        name: firewalld
        state: started
        enabled: true

...
